# 대중교통 데이터 프로젝트

## 2019년 6월, 7월 대중교통 데이터 읽어들이기

In [170]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# 문자열로 인식되는 수를 다시 수로 바꿔줌
def str_to_int(str):
    str = str.replace(',','')
    return int(str)

sub06 = pd.read_csv('201906subway.csv')
sub06 = sub06.iloc[:, :6] # 마지막 열 필요 없음
sub06.columns = ['Month', 'Line', 'ID', 'Station', 'IN', 'OUT'] # Column 설정
sub06['Station'] = sub06['Station'].str.split('(', n=1, expand=True) # 부역명 제거
sub06k = sub06[sub06['Line'].str.contains('경원선') & \
      sub06['Station'].isin(['이촌', '서빙고', '한남', '옥수', '응봉', '왕십리', '청량리'])]
sub06 = sub06.drop(sub06[sub06['Line'].str.contains('경원선') & \
      sub06['Station'].isin(['이촌', '서빙고', '한남', '옥수', '응봉', '왕십리', '청량리'])].index)
sub06k['Line'] = '경의중앙선'
sub06 = pd.concat([sub06, sub06k], axis=0).sort_values(by='ID', ascending=True, axis=0)
sub06['Line'] = sub06['Line'].replace('공항철도 1호선', '공항철도') 
sub06['Line'] = sub06['Line'].replace('경부선', '1호선')
sub06['Line'] = sub06['Line'].replace('경인선', '1호선')
sub06['Line'] = sub06['Line'].replace('장항선', '1호선')
sub06['Line'] = sub06['Line'].replace('경의선', '경의중앙선')
sub06['Line'] = sub06['Line'].replace('중앙선', '경의중앙선')
sub06['Line'] = sub06['Line'].replace('일산선', '3호선')
sub06['Line'] = sub06['Line'].replace('과천선', '4호선')
sub06['Line'] = sub06['Line'].replace('안산선', '4호선')
sub06['Line'] = sub06['Line'].replace('9호선2~3단계', '9호선')
sub06['ALL'] = sub06.apply (lambda row: str_to_int(row.IN) + str_to_int(row.OUT), axis=1) # 승하차 합
sub06['Average'] = sub06.apply (lambda row: round(row.ALL / 30), axis=1) # 일평균 승하차
# sub06 = sub06.sort_values(by='Average', ascending=False, axis=0) # 일평균 승하차 정렬
sub06 = sub06.drop(sub06[sub06['Average'] < 10].index) # 무의미한 데이터 날리기
sub06[['Month', 'Line', 'Station', 'Average']]

       Month   Line    Station  Average
0    2019-06    1호선        서울역   109572
1    2019-06    1호선         시청    50712
2    2019-06    1호선         종각    81693
3    2019-06    1호선       종로3가    65823
4    2019-06    1호선       종로5가    52583
5    2019-06    1호선        동대문    31819
6    2019-06    1호선        신설동    31346
7    2019-06    1호선        제기동    41114
8    2019-06    1호선        청량리    51076
9    2019-06    1호선        동묘앞    23327
10   2019-06    2호선         시청    48670
11   2019-06    2호선      을지로입구    98775
12   2019-06    2호선      을지로3가    45104
13   2019-06    2호선      을지로4가    24347
14   2019-06    2호선  동대문역사문화공원    40982
15   2019-06    2호선         신당    30395
16   2019-06    2호선       상왕십리    28041
17   2019-06    2호선        왕십리    35945
18   2019-06    2호선        한양대    24341
19   2019-06    2호선         뚝섬    38820
20   2019-06    2호선         성수    58412
21   2019-06    2호선       건대입구    92403
22   2019-06    2호선         구의    46846
23   2019-06    2호선         강변    89090
24   2019-06    2호선       잠실나루    31446
25   2019-06    2호선         잠실   163338
26   2019-06    2호선       잠실새내    49320
27   2019-06    2호선      종합운동장    30894
28   2019-06    2호선         삼성   116060
29   2019-06    2호선         선릉    98860
..       ...    ...        ...      ...
580  2019-06    9호선      올림픽공원    16474
581  2019-06    9호선       둔촌오륜     1863
582  2019-06    9호선     중앙보훈병원    13423
556  2019-06   공항철도        서울역    26038
557  2019-06   공항철도         공덕     5550
558  2019-06   공항철도       홍대입구    25230
559  2019-06   공항철도   디지털미디어시티    23072
560  2019-06   공항철도       마곡나루     9808
561  2019-06   공항철도       김포공항    17788
562  2019-06   공항철도         계양    21158
563  2019-06   공항철도         검암    16057
564  2019-06   공항철도     청라국제도시    12665
565  2019-06   공항철도         운서    14658
566  2019-06   공항철도     공항화물청사     4930
567  2019-06   공항철도   인천공항1터미널    34125
568  2019-06   공항철도   인천공항2터미널    10953
569  2019-06   공항철도         영종     5597
583  2019-06  우이신설선      북한산우이     6345
584  2019-06  우이신설선       솔밭공원     4854
585  2019-06  우이신설선   4.19민주묘지     6308
586  2019-06  우이신설선        가오리     8081
587  2019-06  우이신설선         화계     6504
588  2019-06  우이신설선         삼양     4188
589  2019-06  우이신설선      삼양사거리     4941
590  2019-06  우이신설선         솔샘    10693
591  2019-06  우이신설선     북한산보국문    11733
592  2019-06  우이신설선         정릉     8434
593  2019-06  우이신설선     성신여대입구     7795
594  2019-06  우이신설선         보문     3232
595  2019-06  우이신설선        신설동     3978

[588 rows x 4 columns]

In [171]:
sub07 = pd.read_csv('201907subway.csv')
sub07 = sub07.iloc[:, :6] # 마지막 열 필요 없음
sub07.columns = ['Month', 'Line', 'ID', 'Station', 'IN', 'OUT']
sub07['Station'] = sub07['Station'].str.split('(', n=1, expand=True)
sub07k = sub07[sub07['Line'].str.contains('경원선') & \
      sub07['Station'].isin(['이촌', '서빙고', '한남', '옥수', '응봉', '왕십리', '청량리'])]
sub07 = sub07.drop(sub07[sub07['Line'].str.contains('경원선') & \
      sub07['Station'].isin(['이촌', '서빙고', '한남', '옥수', '응봉', '왕십리', '청량리'])].index)
sub07k['Line'] = '경의중앙선'
sub07 = pd.concat([sub07, sub07k], axis=0).sort_values(by='ID', ascending=True, axis=0)
sub07['Line'] = sub07['Line'].replace('공항철도 1호선', '공항철도') 
sub07['Line'] = sub07['Line'].replace('경부선', '1호선')
sub07['Line'] = sub07['Line'].replace('경인선', '1호선')
sub07['Line'] = sub07['Line'].replace('장항선', '1호선')
sub07['Line'] = sub07['Line'].replace('경의선', '경의중앙선')
sub07['Line'] = sub07['Line'].replace('중앙선', '경의중앙선')
sub07['Line'] = sub07['Line'].replace('일산선', '3호선')
sub07['Line'] = sub07['Line'].replace('과천선', '4호선')
sub07['Line'] = sub07['Line'].replace('안산선', '4호선')
sub07['Line'] = sub07['Line'].replace('9호선2~3단계', '9호선')
sub07['ALL'] = sub07.apply (lambda row: str_to_int(row.IN) + str_to_int(row.OUT), axis=1)
sub07['Average'] = sub07.apply (lambda row: round(row.ALL / 31), axis=1)
# sub07 = sub07.sort_values(by='Average', ascending=False, axis=0)
sub07 = sub07.drop(sub07[sub07['Average'] < 10].index) # 무의미한 데이터 날리기
sub07[['Month', 'Line', 'Station', 'Average']]

       Month   Line    Station  Average
0    2019-07    1호선        서울역   109126
1    2019-07    1호선         시청    50914
2    2019-07    1호선         종각    87323
3    2019-07    1호선       종로3가    66976
4    2019-07    1호선       종로5가    51925
5    2019-07    1호선        동대문    30212
6    2019-07    1호선        신설동    31710
7    2019-07    1호선        제기동    39894
8    2019-07    1호선        청량리    48966
9    2019-07    1호선        동묘앞    20382
10   2019-07    2호선         시청    51546
11   2019-07    2호선      을지로입구   102229
12   2019-07    2호선      을지로3가    47673
13   2019-07    2호선      을지로4가    25149
14   2019-07    2호선  동대문역사문화공원    39959
15   2019-07    2호선         신당    30400
16   2019-07    2호선       상왕십리    28844
17   2019-07    2호선        왕십리    35818
18   2019-07    2호선        한양대    18423
19   2019-07    2호선         뚝섬    39986
20   2019-07    2호선         성수    61959
21   2019-07    2호선       건대입구    91687
22   2019-07    2호선         구의    48172
23   2019-07    2호선         강변    88547
24   2019-07    2호선       잠실나루    32431
25   2019-07    2호선         잠실   170497
26   2019-07    2호선       잠실새내    50429
27   2019-07    2호선      종합운동장    29264
28   2019-07    2호선         삼성   130812
29   2019-07    2호선         선릉   108328
..       ...    ...        ...      ...
581  2019-07    9호선      올림픽공원    16573
582  2019-07    9호선       둔촌오륜     1891
583  2019-07    9호선     중앙보훈병원    14470
557  2019-07   공항철도        서울역    25117
558  2019-07   공항철도         공덕     5683
559  2019-07   공항철도       홍대입구    24749
560  2019-07   공항철도   디지털미디어시티    24054
561  2019-07   공항철도       마곡나루    10692
562  2019-07   공항철도       김포공항    18233
563  2019-07   공항철도         계양    21092
564  2019-07   공항철도         검암    16478
565  2019-07   공항철도     청라국제도시    13233
566  2019-07   공항철도         운서    14916
567  2019-07   공항철도     공항화물청사     5114
568  2019-07   공항철도   인천공항1터미널    34474
569  2019-07   공항철도   인천공항2터미널    11054
570  2019-07   공항철도         영종     5638
584  2019-07  우이신설선      북한산우이     5821
585  2019-07  우이신설선       솔밭공원     4884
586  2019-07  우이신설선   4.19민주묘지     5357
587  2019-07  우이신설선        가오리     8136
588  2019-07  우이신설선         화계     6591
589  2019-07  우이신설선         삼양     4191
590  2019-07  우이신설선      삼양사거리     4998
591  2019-07  우이신설선         솔샘    10923
592  2019-07  우이신설선     북한산보국문    11228
593  2019-07  우이신설선         정릉     8257
594  2019-07  우이신설선     성신여대입구     7627
595  2019-07  우이신설선         보문     3211
596  2019-07  우이신설선        신설동     4047

[588 rows x 4 columns]

## 2019년 7월 기준, 각 노선별 이용객이 가장 많은 역 찾기

일반적으로 도심지에 위치한 역이 많은 이용자 수를 보인다.

일부 역은 환승역으로, 지하철끼리의 환승은 계산되지 않아 왜곡이 발생한다.

In [172]:
line_df = []
for value in [str(i+1) + '호선' for i in range(9)] + \
['경의중앙선', '분당선', '수인선', '경춘선', '경강선']: # list of list
    line_df.append([value, \
                    sub07[sub07['Line'] == value]\
                    .sort_values(by='Average', ascending=False, axis=0).iloc[0]['Station'], \
                     sub07[sub07['Line'] == value]\
                    .sort_values(by='Average', ascending=False, axis=0).iloc[0]['Average']])
df = pd.DataFrame(line_df)
df.columns = ['Line', 'Station', 'Average']
df

     Line  Station  Average
0     1호선      서울역   109126
1     2호선       강남   219111
2     3호선    고속터미널   117541
3     4호선       혜화    83242
4     5호선      광화문    71804
5     6호선       공덕    36868
6     7호선  가산디지털단지    82282
7     8호선       문정    39454
8     9호선      신논현    69806
9   경의중앙선       회기    54325
10    분당선       야탑    60418
11    수인선     인천논현    12726
12    경춘선     평내호평    11796
13    경강선     경기광주    13747

## 2019년 7월 기준, 각 노선별 이용객이 가장 적은 역 찾기

일부 역은 환승역으로, 지하철끼리의 환승은 계산되지 않아 왜곡이 발생한다.

In [173]:
line_df2 = []
for value in [str(i+1) + '호선' for i in range(9)] + \
['경의중앙선', '분당선', '수인선', '경춘선', '경강선']: # list of list
    line_df2.append([value, \
                    sub07[sub07['Line'] == value].sort_values(by='Average', ascending=False, axis=0).iloc[-1]['Station'], \
                     sub07[sub07['Line'] == value].sort_values(by='Average', ascending=False, axis=0).iloc[-1]['Average']])
df2 = pd.DataFrame(line_df2)
df2.columns = ['Line', 'Station', 'Average']
df2

     Line    Station  Average
0     1호선         직산     1905
1     2호선        도림천     2605
2     3호선         지축     2701
3     4호선        남태령     2665
4     5호선  동대문역사문화공원     6266
5     6호선       버티고개     4692
6     7호선         장암     3602
7     8호선         모란     8438
8     9호선       둔촌오륜     1891
9   경의중앙선         옥수       86
10    분당선         구룡     3333
11    수인선         달월      153
12    경춘선        백양리      293
13    경강선      세종대왕릉      631

## 2019년 6월, 7월 변화율 살펴보기

In [175]:
# 재정렬
sub06 = sub06.sort_values(by='ID', ascending=True, axis=0)
sub07 = sub07.sort_values(by='ID', ascending=True, axis=0)

# 병합
suball = pd.concat([sub06[['Line', 'ID', 'Station', 'Average']], sub07[['Average']]], axis=1)
suball.columns = ['Line', 'ID', 'Station', 'June', 'July']
suball['Comparison'] = suball.apply (lambda row: row.July - row.June, axis=1)
suball = suball.sort_values(by='Comparison', ascending=False, axis=0)
suball.head()

     Line      ID Station     June     July  Comparison
548   9호선  4118.0      노들   8615.0  59330.0     50715.0
556  공항철도  4201.0     서울역  26038.0  69806.0     43768.0
398   5호선  2535.0    종로3가  31651.0  71804.0     40153.0
386   5호선  2523.0      양평  12628.0  50642.0     38014.0
383   5호선  2520.0      신정  22200.0  59177.0     36977.0

## 2019년 7월 기준, 환승객 포함한 통계 만들기

In [176]:
subtemp = sub07.groupby('Station')['Average'].sum()
subtemp = subtemp.sort_values(ascending=False, axis=0)
subtemp

Station
강남           219111
잠실           205044
홍대입구         194396
고속터미널        191890
서울역          188068
사당           145668
신림           139667
선릉           139128
삼성           130812
구로디지털단지      129453
신도림          124707
종로3가         124376
건대입구         124216
가산디지털단지      119285
서울대입구        106116
역삼           105900
수원           105354
교대           104503
시청           102460
을지로입구        102229
영등포          101271
합정           100129
신촌            97631
여의도           95752
노원            91917
동대문역사문화공원     89535
강변            88547
용산            87365
종각            87323
당산            85392
              ...
금곡             3114
지축             2701
봉명             2684
남태령            2665
도림천            2605
신창             2491
신둔도예촌          2367
파주             2315
배방             2070
팔당             1970
직산             1905
둔촌오륜           1891
대성리            1861
운길산            1738
양정             1698
신내             1678
국수             1666
아신             1348
곡산             1205
강촌             1100
원덕              859
김유정             817
상천              737
오빈              663
세종대왕릉           631
신원              394
굴봉산             358
백양리             293
달월              153
지평              118
Name: Average, Length: 509, dtype: int64

In [177]:
sub07.sort_values(by='Average', ascending=True, axis=0)[['Line', 'Station', 'Average']]

      Line  Station  Average
182  경의중앙선       옥수       86
296  경의중앙선       지평      118
351    수인선       달월      153
346    경춘선      백양리      293
345    경춘선      굴봉산      358
289  경의중앙선       신원      394
373    경강선    세종대왕릉      631
292  경의중앙선       오빈      663
343    경춘선       상천      737
348    경춘선      김유정      817
294  경의중앙선       원덕      859
347    경춘선       강촌     1100
316  경의중앙선       곡산     1205
291  경의중앙선       아신     1348
290  경의중앙선       국수     1666
332    경춘선       신내     1678
283  경의중앙선       양정     1698
287  경의중앙선      운길산     1738
341    경춘선      대성리     1861
582    9호선     둔촌오륜     1891
153    1호선       직산     1905
286  경의중앙선       팔당     1970
300    1호선       배방     2070
365    경강선       이매     2143
304  경의중앙선       신촌     2156
326  경의중앙선       파주     2315
370    경강선    신둔도예촌     2367
302    1호선       신창     2491
56     2호선      도림천     2605
119    4호선      남태령     2665
..     ...      ...      ...
109    4호선       명동    73428
99     4호선       수유    75415
164    1호선       부평    78081
162    1호선       부천    79083
32     2호선       교대    79481
62     3호선      연신내    81912
501    7호선  가산디지털단지    82282
105    4호선       혜화    83242
83     3호선       양재    83375
2      1호선       종각    87323
122    1호선       용산    87365
23     2호선       강변    88547
140    1호선       수원    90025
35     2호선       사당    91338
21     2호선     건대입구    91687
49     2호선       신촌    95475
125    1호선      영등포   101271
11     2호선    을지로입구   102229
30     2호선       역삼   105900
37     2호선    서울대입구   106116
29     2호선       선릉   108328
0      1호선      서울역   109126
43     2호선      신도림   116165
80     3호선    고속터미널   117541
41     2호선  구로디지털단지   129453
28     2호선       삼성   130812
39     2호선       신림   139667
48     2호선     홍대입구   165115
25     2호선       잠실   170497
31     2호선       강남   219111

[588 rows x 3 columns]